version: '2'
services:
    lpb-app:
        image: lpb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://lpb-mysql:3306/lpb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=lpb-elasticsearch:9300
        ports:
            - 8080:8080
    lpb-mysql:
        extends:
            file: mysql.yml
            service: lpb-mysql
    lpb-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: lpb-elasticsearch
